export { default as binoculars} from '../icons/binoculars-solid.svg'
export {default as bug} from '../icons/bug-solid.svg'
export {default as cloudSun} from '../icons/cloud-sun-solid.svg'
export {default as feather} from '../icons/feather-solid.svg'
export {default as fire} from '../icons/fire-solid.svg'
export {default as frog} from '../icons/frog-solid.svg'
export {default as leaf} from '../icons/leaf-solid.svg'
export {default as mosquito} from '../icons/mosquito-solid.svg'
export {default as mountainCity} from '../icons/mountain-city-solid.svg'
export {default as mountain} from '../icons/mountain-solid.svg'
export {default as mountainSun} from '../icons/mountain-sun-solid.svg'
export {default as person} from '../icons/person-hiking-solid.svg'
export {default as seed} from '../icons/seedling-solid.svg'
export {default as signs} from '../icons/signs-post-solid.svg'
export {default as tree} from '../icons/tree-solid.svg'
export {default as volcano} from '../icons/volcano-solid.svg'
export {default as water} from '../icons/water-solid.svg'
export {default as wind} from '../icons/wind-solid.svg'